#define NAME_COUNT 63
#define NAME_LENGTH 10  // including '\0'

const char Tablenames[NAME_COUNT][NAME_LENGTH] = {
  "Bank 1 ",
  "Bank 2 ",
  "Bank 3 ",
  "Bank 4 ",
  "Bank 5 ",
  "Bank 6 ",
  "Bank 7 ",
  "Bank 8 ",
  "Bank 9 ",
  "Bank 10 ",
  "Bank 11 ",
  "Bank 12 ",
  "Bank 13 ",
  "Bank 14 ",
  "Bank 15 ",
  "Bank 16 ",
  "Bank 17 ",
  "Bank 18 ",
  "Bank 19 ",
  "Bank 20 ",
  "A Guitar ",
  "AltoSax ",
  "Birds ",
  "Reduced ",
  "Blended ",
  "Saw ",
  "Saw Brigh",
  "Saw Gap",
  "Saw Round",
  "Sine",
  "Square",
  "Squ Round",
  "Triangle",
  "C604",
  "Cello",
  "Clarinett",
  "Clavinet",
  "D. Bass",
  "Distorted",
  "Elec Bass",
  "E. Guitar",
  "E. Organ",
  "E. Piano",
  "Flute",
  "FM Synth",
  "Granualar",
  "H Drawn",
  "H Voice",
  "Linear",
  "Oboe",
  "Osc Chip",
  "Overtone",
  "A Piano",
  "Plucked",
  "Raw",
  "Sine Harm",
  "Snippets",
  "StringBox",
  "Symetric",
  "Theremin",
  "V Game",
  "B. VGame",
  "Violin",
};
